{{ if and (not .Values.common.siteconfigonly) (eq .Values.common.ingressType "route") }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: skupper
spec:
  to:
    kind: Service
    name: skupper
    weight: 100
  port:
    targetPort: metrics
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}