{{ if not .Values.common.siteconfigonly }}
apiVersion: v1
data:
  prometheus.yml: |2

    global:
      scrape_interval:     15s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
      - static_configs:
        - targets:
    rule_files:
      # - "example-file.yml"
    scrape_configs:
      - job_name: 'prometheus'
        metrics_path: "/api/v1alpha1/metrics"
        scheme: "https"
        tls_config:
          insecure_skip_verify: true
        static_configs:
        - targets: ["skupper.{{ .Release.Namespace }}.svc.cluster.local:8010"]
  web-config.yml: |2

    # TLS configuration.
    #
    #tls_server_config:
    #  cert_file: /etc/tls/certs/tls.crt
    #  key_file: /etc/tls/certs/tls.key
    #
    #
    # Usernames and passwords required to connect to Prometheus.
    # Passwords are hashed with bcrypt: https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-configuration.md#about-bcrypt
    #basic_auth_users:
    #
kind: ConfigMap
metadata:
  name: prometheus-server-config
{{- end }}