{{ if not .Values.common.siteconfigonly }}
apiVersion: v1
kind: Service
metadata:
  name: skupper-prometheus
spec:
  ports:
  - name: prometheus
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: skupper-prometheus
    app.kubernetes.io/part-of: skupper
    skupper.io/component: prometheus
  sessionAffinity: None
  type: ClusterIP
{{- end }}