# Declare variables to be passed into your templates.

# image versions are based on the releases from skupper.io, Every release of skupper will have four containers(at the time of document 20/10). Check the mainfest for each release and push them to DTR.
common:
  siteconfigonly: false
  ingressType: "route"
  ingress:
    domain: "apps.example.com"  #  Domain of the cluster, like "apps-int.di1001.cpaas.test".

console:
  enabled: true
  auth: unsecured  #  internal / openshift

router:
  name: skupper-router
  image:
    repository: quay.io/skupper/skupper-router
    pullPolicy: IfNotPresent
    version: 2.4.2
  mode: "interior"
  replicas: 1
  cpu:
    requests: 100m
    limits: 2
  memory:
    requests: 2Gi
    limits: 4Gi
  annotations:
    prometheus.io/port: "9090"  #  required for flow controller to get logs
    prometheus.io/scrape: "true"  #  required for flow controller to get logs
  labels: {}

configSync:
  image:
    repository: "quay.io/skupper/config-sync"
    version: "1.4.2"
    pullPolicy: IfNotPresent
  cpu:
    requests: 50m
    limits: 100m
  memory:
    requests: 128Mi
    limits: 256Mi

serviceController:
  enabled: true
  disableServiceSync: false
  image:
    repository: "quay.io/skupper/service-controller"
    pullPolicy: IfNotPresent
    version: "1.4.2"
  cpu:
    requests: 100m
    limits: 100m
  memory:
    requests: 256Mi
    limits: 256Mi

flowCollector:  #  this will help in generating metrics
  enabled: false
  # image:
  #   repository: "quay.io/skupper/flow-collector"
  #   tag: "1.4.2"
  # cpu:
  #   requests: 300m
  #   limits: 1
  # memory:
  #   requests: 1Gi
  #   limits: 1Gi
prometheus:  #  this will help in generating metrics 
  image:
    repository: "quay.io/prometheus/prometheus"
    version: "v2.42.0"
  cpu:
    requests: 200m
    limits: 200m
  memory:
    requests: 256Mi
    limits: 256Mi


remoteSites:
 - name: udeploy-agents-dev-di1001
   edgehost:  remoteistedetails
   interrouterhost:  remoteistedetails

selfSignedCerts: true

linkTokenCreate: true 


secrets:
  - skupper-claims-server
  - skupper-local-client
  - skupper-console-certs
  - skupper-local-server
  - skupper-service-client
  - skupper-site-server
  - skupper-link-token
